# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
name: 'gatsby'

# The runtime the application uses.
# Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
type: 'nodejs:18'

# Resources and CPU to allocate to the service
# Complete list of available sizes: https://docs.platform.sh/create-apps/app-reference.html#sizes
size: L

# Fine-tune allocated resources
# https://docs.platform.sh/create-apps/flexible-resources.html#performance-profiles
resources:
  base_memory: 1024
  memory_ratio: 1024

# The size of the persistent disk of the application (in MB). Minimum value is 128.
disk: 1280

# Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
# More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
mounts:
  '/.cache':
    source: local
    source_path: cache
  '/.config':
    source: local
    source_path: config
  'public':
    source: local
    source_path: public

# The web key configures the web server running in front of your app.
# More information: https://docs.platform.sh/create-apps/app-reference.html#web
web:
  locations:
    '/site':
      # The public directory of the application relative to its root.
      root: 'public'
      index: [ 'index.html' ]
      scripts: false
      allow: true

# Define variables used by this app (env, runtime settings, ...)
# https://docs.platform.sh/create-apps/app-reference.html#variables
variables:
  env:
    NODE_OPTIONS: --max-old-space-size=1536

# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.platform.sh/create-apps/app-reference.html#build
build:
  flavor: none

# Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
# are available in the PATH during the build process and in the runtime environment. They’re installed before
# the build hook runs using a package manager for the language.
# More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
dependencies:
  nodejs:
    yarn: "1.22.17"

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More information:
hooks:
  build: |
    set -e
    yarn --frozen-lockfile
  # Post deploy hook builds Gatsby frontend now that backend content is available.
  post_deploy: |
    # printf "export PLATFORM_ROUTES=$PLATFORM_ROUTES" > .env/env.production
    yarn build --prefix-paths
